### ISSUE TITLE
Failed to deploy gradle

### ISSUE THREAD

**Issue by haritrichy** [mhavey/marklogic#12]
Hello,
I followed your [tutorial](https://github.com/mhavey/marklogic/blob/master/uml2es/tutorials/papyrus_model_edit.md) and tried to deploy uml2es solution locally in my virtual desktop that has ML 10 and faced the following failure. Could you please help me to fix? Thanks

18:01:17.726 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
18:01:17.726 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':includeUGradle'.
18:01:17.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to create MD5 hash for file content.

**Comment by mhavey** [comment]
I'll investigate. Were you running "gradle -i setup mlDeploy" when this happened?

**Comment by mhavey** [comment]
Are you running gradle on a Windows machine? If so, I believe this issue is file-locking related. I am working on a fix. Meanwhile here is a workaround to get you unblocked.

1. Manually copy file uml2es.gradle from marklogic/uml2es/uml2esTransform folder into marklogic/uml2es/tutorials/gradle folder. 

2. Instead of running gradle -i setup mlDeploy, run this:
gradle -i includeXMI2ESTransform mlDeploy

Let me know if this gets you moving forward with the tutorial

**Comment by haritrichy** [comment]
Thanks Mike. It works now!
